### Variables
@baseUrl = http://localhost:8080
@eventAiId = c37c9d8c-5336-45cf-92f3-b85b67799ccf
@eventTechId = 28682344-cc2e-41e2-af41-d84a449ea967

### 1. Récupérer les intervenants de l'événement AI & Data Workshop
GET {{baseUrl}}/events/{{eventAiId}}/speakers
Accept: application/json

### 2. Récupérer les intervenants de l'événement Tech Summit Paris 2026
GET {{baseUrl}}/events/{{eventTechId}}/speakers
Accept: application/json

### 3. Récupérer les sessions de l'événement AI & Data Workshop (alternative)
GET {{baseUrl}}/events/{{eventAiId}}/sessions
Accept: application/json