### Get questions sorted by upvotes
GET http://localhost:8080/sessions/2/questions?sort=upvotes&visitorId=visitor-001


### Create question
POST http://localhost:8080/sessions/2/questions
Content-Type: application/json

{
  "content": "Quels sont les principaux cas d’usage de l’IA générative aujourd’hui ?",
  "authorName": "Lucas"
}


### Upvote question
POST http://localhost:8080/questions/1/upvote
Content-Type: application/json

{
  "visitorId": "visitor-001"
}


### Try duplicate upvote
POST http://localhost:8080/questions/1/upvote
Content-Type: application/json

{
  "visitorId": "visitor-001"
}


### Get questions after upvote
GET http://localhost:8080/sessions/2/questions?sort=upvotes&visitorId=visitor-001